language: go
go:
  # ./... is not supported by Go 1.7, 1.8 and 1.9, etc.
  # - 1.7.x
  # - 1.8.x
  # - 1.9.x
  - 1.10.x
  - 1.11.x
env:
  - GO111MODULE=on
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
